Add ability to set labels on docker container
reside-ic/constellation pull request #16
Opened 2022-11-15 17:29 UTC by r-ash

2022-11-15 18:17 UTC, r-ash commented
Actually just seen https://github.com/reside-ic/beats/blob/main/filebeat.docker.yml#L14, we could do this same thing for hintr instead of making this work through the container labels. Might be a bit more visible if we use the processor

2022-11-15 18:26 UTC, richfitz requested changes
Looks fine but you will need to increase the version number to be able to update on pypi

2022-11-16 09:59 UTC, r-ash commented
> Looks fine but you will need to increase the version number to be able to update on pypi

Version number has increased? The one in `setup.py`?

2022-11-16 10:54 UTC, richfitz approved these changes
Sorry, missed that :facepalm:

2022-11-16 10:54 UTC, merged